FROM tomcat 
COPY student.war /usr/local/tomcat/webapps/student.war
COPY context.xml /usr/local/tomcat/conf/context.xml
COPY catalina.sh /usr/local/tomcat/bin/catalina.sh
COPY mysql-connector-java-5.1.47.jar /usr/local/tomcat/lib/mysql-connector-java-5.1.47.jar
