apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service-deploy-v5
  labels:
    app: webapp-v5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-v5
  template:
    metadata:
      labels:
        app: webapp-v5
    spec:
      containers:
      - name: web
        image: raghudevops32/httpd:v5
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: web-deploy-svc-v5
spec:
  type: LoadBalancer
  selector:
    app: webapp-v5
  ports:
  - port: 80
    targetPort: 80
