apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service-deploy-v6
  labels:
    app: webapp-v6
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-v6
  template:
    metadata:
      labels:
        app: webapp-v6
    spec:
      containers:
      - name: web
        image: raghudevops32/httpd:v6
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: web-deploy-svc-v6
spec:
  type: LoadBalancer
  selector:
    app: webapp-v6
  ports:
  - port: 80
    targetPort: 80
