--- 
apiVersion: v1
data:
  web.conf: |
    ProxyPass /student http://student-app.default.svc.cluster.local/student
    ProxyPassReverse /student http://student-app.default.svc.cluster.local/student
  api.conf: |
    ProxyPass /api http://student-api.default.svc.cluster.local
    ProxyPassReverse /api http://student-api.default.svc.cluster.local
kind: ConfigMap
metadata:
  name: student-config
---
kind: Pod
apiVersion: v1
metadata:
  name: web
  labels:
    name: web
spec:
  containers:
  - name: web
    image: raghudevops32/httpd:v3
    volumeMounts:
      - name: student-config
        mountPath: /etc/config
  volumes:
    - name: student-config
      configMap:
        name: student-config

--- 
kind: Service
apiVersion: v1
metadata:
  name: web
spec:
  type: LoadBalancer
  selector:
    name: web
  ports:
  - name: web-app
    port: 80
    targetPort: 80
